# Generated by Django 3.1.3 on 2021-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210901_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='choices_ids',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
