# Generated by Django 3.1.3 on 2021-09-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_submission_choices_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choices_ids',
        ),
    ]
